language: php

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

script:
  - phpunit --configuration ./build/travis-ci.xml

matrix:
  allow_failures:
    - php:
        - 7.1

notifications:
  email:
    recipients:
      - nbraczek@bsds.de
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: change     # default: false

