language: php

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script: phpunit --configuration ./build/travis-ci.xml

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
